@baseUrl = http://localhost:3000
@contentType = application/json
@adminUsername = "admin"
@adminEmail = "admin@email.com"
@adminPassword = "admin123"

# Run register + login first, then the token below is reused automatically.
# @name register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "username": "api-user",
  "email": "api-user@example.com",
  "password": "secret123"
}


###
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "usernameOrEmail": "api-user",
  "password": "secret123"
}


###
@token = {{login.response.body.access_token}}
@registeredUserId = {{register.response.body.id}}


###
# @name adminlogin
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "usernameOrEmail": {{adminUsername}},
  "password": {{adminPassword}}
}


###
@adminToken = {{adminlogin.response.body.access_token}}

# root
GET {{baseUrl}}/
Authorization: Bearer {{token}}


###
# USERS API
# @name createUser
POST {{baseUrl}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "username": "john_doe",
  "email": "john.doe@example.com",
  "password": "password123",
  "role": "USER"
}


###
@createdUserId = {{createUser.response.body.id}}

###
# login new user to get his token
# @name newUserlogin
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "usernameOrEmail": "john_doe",
  "password": "password123"
}

###
@createdUserToken = {{newUserlogin.response.body.access_token}}

GET {{baseUrl}}/users
Authorization: Bearer {{token}}
# forbidden for the user

###
GET {{baseUrl}}/users
Authorization: Bearer {{adminToken}}

###
GET {{baseUrl}}/users/{{createdUserId}}
Authorization: Bearer {{token}}
# forbidden for the user to access others data
###
###
GET {{baseUrl}}/users/{{createdUserId}}
Authorization: Bearer {{createdUserToken}}

###
PATCH {{baseUrl}}/users/{{createdUserId}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "username": "john_doe_updated"
}


###
DELETE {{baseUrl}}/users/{{createdUserId}}
Authorization: Bearer {{token}}


###
# SKILL API
# @name createSkill
POST {{baseUrl}}/skill
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "designation": "NestJS"
}


###
@skillId = {{createSkill.response.body.id}}

GET {{baseUrl}}/skill
Authorization: Bearer {{token}}


###
GET {{baseUrl}}/skill/{{skillId}}
Authorization: Bearer {{token}}


###
PATCH {{baseUrl}}/skill/{{skillId}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "designation": "NestJS Advanced"
}


###
# CVS API (JWT protected)
# @name createCv
POST {{baseUrl}}/cvs
Content-Type: {{contentType}}
Authorization: Bearer {{createdUserToken}}

{
  "firstName": "John",
  "name": "Doe",
  "age": 27,
  "Job": "Backend Developer",
  "cin": "12345678",
  "path": "/tmp/john-cv.pdf",
  "skills": [
    {
      "id": "{{skillId}}"
    },
    {
      "designation": "Prisma"
    }
  ]
}


###
@cvId = {{createCv.response.body.id}}

GET {{baseUrl}}/cvs
Authorization: Bearer {{token}}

### 
# new user to retrieve only his cvs
GET {{baseUrl}}/cvs
Authorization: Bearer {{createdUserToken}}


###
# For admin to retrieve all CVs
GET {{baseUrl}}/cvs
Authorization: Bearer {{adminToken}}


###
GET {{baseUrl}}/cvs/{{cvId}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/cvs/{{cvId}}
Authorization: Bearer {{createdUserToken}}

###for admin
GET {{baseUrl}}/cvs/{{cvId}}
Authorization: Bearer {{adminToken}}


###
PATCH {{baseUrl}}/cvs/{{cvId}}
Content-Type: {{contentType}}
Authorization: Bearer {{createdUserToken}}

{
  "Job": "Senior Backend Developer",
  "skills": [
    {
      "id": "{{skillId}}"
    }
  ]
}


### for admin that cant update the cv of others
PATCH {{baseUrl}}/cvs/{{cvId}}
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "Job": "Senior Backend Developer 2",
  "skills": []
}


###
DELETE {{baseUrl}}/cvs/{{cvId}}
Authorization: Bearer {{createdUserToken}}


###
# cleanup for skill
DELETE {{baseUrl}}/skill/{{skillId}}
Authorization: Bearer {{token}}